version: "3.9"
services:
  tianlongintent_sementic_web-1:
    image: flczmsxh/rct_comp_plat_exam_2022:latest
    volumes:
      - /root/rct-comp-platform-exam-2022-main/data:/rct/data
    command: python3 torch_server.py -p 8080
    deploy:
      resources:
        reservations:
          devices:
            - device_ids: ['0']
              capabilities:
              - gpu
  tianlongintent_sementic_web-2:
    image: flczmsxh/rct_comp_plat_exam_2022:latest
    volumes:
      - /root/rct-comp-platform-exam-2022-main/data:/rct/data
    command: python3 torch_server.py -p 8080
    deploy:
      resources:
        reservations:
          devices:
            - device_ids: ['1']
              capabilities:
              - gpu
  tianlongintent_sementic_web-3:
    image: flczmsxh/rct_comp_plat_exam_2022:latest
    volumes:
      - /root/rct-comp-platform-exam-2022-main/data:/rct/data
    command: python3 torch_server.py -p 8080
    deploy:
      resources:
        reservations:
          devices:
            - device_ids: ['2']
              capabilities:
              - gpu
  tianlongintent_sementic_web-4:
    image: flczmsxh/rct_comp_plat_exam_2022:latest
    volumes:
      - /root/rct-comp-platform-exam-2022-main/data:/rct/data
    command: python3 torch_server.py -p 8080
    deploy:
      resources:
        reservations:
          devices:
            - device_ids: ['3']
              capabilities:
              - gpu
  nginx:
    image: axizdkr/tengine
    container_name: tianlong-nginx
    volumes:
      - "./nginx-gpu-4.conf:/etc/nginx/conf.d/nginx.conf"
      - "/usr/share/zoneinfo/Asia/Shanghai:/usr/share/zoneinfo/Asia/Shanghai"
      - "/etc/localtime:/etc/localtime:ro"
    depends_on:
      - tianlongintent_sementic_web-1
      - tianlongintent_sementic_web-2
      - tianlongintent_sementic_web-3
      - tianlongintent_sementic_web-4
    ports:
      - mode: host
        protocol: tcp
        published: 8032
        target: 8032
    environment:
      TZ: 'Asia/Shanghai'
    restart: always
